version: "3.8"

services:
  nginx:
    image: nginx:1.25-alpine
    container_name: laravelapi-nginx
    restart: unless-stopped
    ports:
      - ${NGINX_PORT_OUT}:80
    volumes:
      - ./scripts/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    networks:
      - laravelapi

  mariadb:
    image: mariadb:10.11
    container_name: laravelapi-mariadb
    restart: unless-stopped
    tty: true
    ports:
      - ${DB_PORT_OUT}:3306
    volumes:
      - data:/var/lib/mysql
    networks:
      - laravelapi
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mariadb

  app:
    build:
      context: .
      dockerfile: Dockerfile
      #args:
        #USER_ID: ${USER_ID:-0}
        #GROUP_ID: ${GROUP_ID:-0}
    #user: $USER_ID:$GROUP_ID
    container_name: laravelapi-app
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - ./src:/var/www/html
      # Setup user in container
      #- /etc/group:/etc/group:ro
      #- /etc/passwd:/etc/passwd:ro
      #- /etc/shadow:/etc/shadow:ro
    networks:
      - laravelapi
    depends_on:
      - nginx
      - mariadb

volumes:
  data:

networks:
  laravelapi: